### ISSUE TITLE
Code does not run

### ISSUE THREAD

**Issue by RepublicOfMars** [CSAllenISDClassroom/sudokuserver-wendy-s-4-for-4#2]
![image](https://user-images.githubusercontent.com/54324557/135915309-a29c4578-4fc7-4625-820a-b8fc0ca91714.png)
There are more errors than on screen, I'm guessing an open bracket is missing somewhere or there is an extra closed bracket.

**Comment by Rohan-Kalyanpura** [comment]
there was a lot of extra files due to having to merge two repositories together this caused some issues
